config/routes.rb
Cyprussite::Application.routes.draw do
  get "contact/index"

  get "about/index"

  get "catalog/index"

  resources :properties

  resources :searchresults
  
  root :to => "searchresults#new"
  resources :catalog
  match '/catalog_price' => 'catalog#price'
  match '/catalog_type' => 'catalog#type'

  match '/about' => 'about#index'
  resources :contact
  
  

end

app/models/searchresult.rb
class Searchresult < ActiveRecord::Base
end

app/controllers/searchresults_controller.rb
class SearchresultsController < ApplicationController
  # GET /searchresults
  # GET /searchresults.json
  def index
    @searchresults = Searchresult.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @searchresults }
    end
  end

  # GET /searchresults/1
  # GET /searchresults/1.json
  def show
    @searchresult = Searchresult.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @searchresult }
    end
  end

  # GET /searchresults/new
  # GET /searchresults/new.json
  def new
    @searchresult = Searchresult.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @searchresult }
    end
  end

  # GET /searchresults/1/edit
  def edit
    @searchresult = Searchresult.find(params[:id])
  end

  # POST /searchresults
  # POST /searchresults.json
  def create
    @searchresult = Searchresult.new(params[:searchresult])

    respond_to do |format|
      if @searchresult.save
        format.html { redirect_to @searchresult, notice: 'Searchresult was successfully created.' }
        format.json { render json: @searchresult, status: :created, location: @searchresult }
      else
        format.html { render action: "new" }
        format.json { render json: @searchresult.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /searchresults/1
  # PUT /searchresults/1.json
  def update
    @searchresult = Searchresult.find(params[:id])

    respond_to do |format|
      if @searchresult.update_attributes(params[:searchresult])
        format.html { redirect_to @searchresult, notice: 'Searchresult was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @searchresult.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searchresults/1
  # DELETE /searchresults/1.json
  def destroy
    @searchresult = Searchresult.find(params[:id])
    @searchresult.destroy

    respond_to do |format|
      format.html { redirect_to searchresults_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/searchresults_helper.rb
module SearchresultsHelper
end

app/views/searchresults/_form.html.erb
<div class="search_selects">
<%= form_for(@searchresult) do |f| %>
  <% if @searchresult.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@searchresult.errors.count, "error") %> prohibited this searchresult from being saved:</h2>

      <ul>
      <% @searchresult.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field firstf">
    <%= f.label "Категория" %>
    <%#= f.text_field :realtytype %>
    <%= f.select("realtytype", ['аппартаменты', 'офис', 'дом', 'мезоньет', 'другое'], {}, { :class => 'select' })%>
  </div>
  <div class="field">
    <%= f.label "Район" %>
    <%#= f.text_field :location %>
    <%= f.select("location", ['Лимассол'], {}, { :class => 'select' })%>
  </div>
  <div class="field">
    <%= f.label "Количество спален" %>
    <%#= f.text_field :roomcount %>
    <%= f.select("roomcount", ['не важно', '2 спальни', '3 спальни', '4 спальни', '5 спален', '6 спален'], {}, { :class => 'select' })%>
  </div>
  <div class="field">
    <%= f.label "До какой цены (евро)" %>
    <%#= f.number_field :priceline , :step => 10000 , :maxlength=>6, :in => 10000...100000 %>
     <%#= f.number_field 'priceline', nil, :in => 1...10%>
     <%= f.select("priceline", ['150 000', '250 000', '350 000', '500 000', '750 000', '1000 000', '1500 000'], {}, { :class => 'select' })%>
  </div>
  <div class="actions search_btn">
    <%= f.submit %>
  </div>
<% end %>
  </div>

app/views/searchresults/_property.html.erb
<link rel="stylesheet" href="galleriffic-2.css" type="text/css" />
<script type="text/javascript" src="jquery-1.3.2.js"></script>
<script type="text/javascript" src="jquery.galleriffic.js"></script>
<script type="text/javascript" src="jquery.opacityrollover.js"></script>
<!-- We only want the thunbnails to display when javascript is disabled -->
<script type="text/javascript">
	document.write('<style>.noscript { display: none; }</style>');
</script>
<div class="right">
	<div class="images_galery">
		
		<!-- Start Advanced Gallery Html Containers -->
		<div id="gallery" class="content">
			<div class="img_shadow"></div>
			<div id="controls" class="controls"></div>
			<div class="slideshow-container">
				<div id="loading" class="loader"></div>
				<div id="slideshow" class="slideshow"></div>
			</div>
			<div id="caption" class="caption-container"></div>
		</div>
		<div id="thumbs" class="navigation">
			<ul class="thumbs noscript">
				<li>
					<a class="thumb" name="leaf"  href="<%= url_for property.photo.url%>" title="Title #0">
						<%= image_tag property.photo.url(:small) %>
					</a>
					<div class="caption">
						<div class="download">
							<a href= "<%= url_for property.photo.url%>"> </a>
							
						</div>
					</div>
				</li>

				<li>
					<a class="thumb" name="drop" href="<%= url_for property.photo.url%>" title="Title #1">
						<%= image_tag property.photo.url(:small)%>
					</a>
					<div class="download">
						<a href= "<%= url_for property.photo.url%>"> </a>
					</div>
					
				</li>

				<li>
					<a class="thumb" href="<%= url_for property.photo.url%>" title="Title #2">
						<%= image_tag property.photo.url(:small)%>

					</a>
					<div class="caption">
						<div class="download">
							<a href= "<%= url_for property.photo.url%>"> </a>
						</div>
					</div>
				</li>

				<li class="li_last">
					<a class="thumb" href="<%= url_for property.photo.url%>" title="Title #3">
						<%= image_tag property.photo.url(:small)%>

					</a>
					<div class="caption">
						<div class="download">
							<a href= "<%= url_for property.photo.url%>"> </a>
						</div>
					</div>
				</li>

				<li>
					<a class="thumb" href="<%= url_for property.photo.url%>" title="Title #4">
						<%= image_tag property.photo.url(:small)%>

					</a>
					<div class="caption">
						<div class="download">
							<a href= "<%= url_for property.photo.url%>"> </a>
						</div>
					</div>
				</li>
				<li>
					<a class="thumb" href="<%= url_for property.photo.url%>" title="Title #5">
						<%= image_tag property.photo.url(:small)%>

					</a>
					<div class="caption">
						<div class="download">
							<a href= "<%= url_for property.photo.url%>"> </a>
						</div>
					</div>
				</li>

					<li>
						<a class="thumb" href="<%= url_for property.photo.url%>" title="Title #6">
							<%= image_tag property.photo.url(:small)%>

						</a>
						<div class="caption">
							<div class="download">
								<a href= "<%= url_for property.photo.url%>"> </a>
							</div>
						</div>
					</li>

				<li class="li_last">
					<a class="thumb" href="<%= url_for property.photo.url%>" title="Title #7">
						<%= image_tag property.photo.url(:small) %>
						
					</a>
					<div class="caption">
						<div class="download">
							<a href= "<%= url_for property.photo.url%>"> </a>
						</div>
						<!-- <div class="image-title">Title #7</div>
						<div class="image-desc">Description</div>-->
					</div>
				</li>
			</ul>
		</div>
		<div style="clear: both;"></div>
	</div>
</div>




<div class="left show_info">



<h1>
  <%= property.name %>
</h1>
<div class="direct_info">
<p>
  <b class="title">Место положения:</b>
  <%= property.location %>
</p>
<p>
  <b class="title">Количество спален:</b>
  <%= property.roomcount %>
</p>
<p> <b class="title">Тип:</b>
  <%= property.realtytype %>
</p>
</div>

<div class="price_box">
  <%= property.price %> Euro
</div>
<div class="hr"></div>
<p>
  <%= property.fulldescription %>
</p>
</div>
<div style="clear: both;"></div>


<%#= link_to 'Edit', edit_property_path(@property) %> |
<%#= link_to 'Back', properties_path %>





<script type="text/javascript">
	jQuery(document).ready(function($) {
		// We only want these styles applied when javascript is enabled
		$('div.navigation').css({'width' : '443px', 'display' : 'block'});
		$('div.content').css('display', 'block');

		// Initially set opacity on thumbs and add
		// additional styling for hover effect on thumbs
		var onMouseOutOpacity = 0.67;
		$('#thumbs ul.thumbs li').opacityrollover({
			mouseOutOpacity:   onMouseOutOpacity,
			mouseOverOpacity:  1.0,
			fadeSpeed:         'fast',
			exemptionSelector: '.selected'
		});
		
		// Initialize Advanced Galleriffic Gallery
		var gallery = $('#thumbs').galleriffic({
			delay:                     2500,
			numThumbs:                 15,
			preloadAhead:              10,
			enableTopPager:            true,
			enableBottomPager:         true,
			maxPagesToShow:            7,
			imageContainerSel:         '#slideshow',
			controlsContainerSel:      '#controls',
			captionContainerSel:       '#caption',
			loadingContainerSel:       '#loading',
			renderSSControls:          true,
			renderNavControls:         true,
			playLinkText:              'Play Slideshow',
			pauseLinkText:             'Pause Slideshow',
			prevLinkText:              '&lsaquo; Previous Photo',
			nextLinkText:              'Next Photo &rsaquo;',
			nextPageLinkText:          'Next &rsaquo;',
			prevPageLinkText:          '&lsaquo; Prev',
			enableHistory:             false,
			autoStart:                 false,
			syncTransitions:           true,
			defaultTransitionDuration: 900,
			onSlideChange:             function(prevIndex, nextIndex) {
				// 'this' refers to the gallery, which is an extension of $('#thumbs')
				this.find('ul.thumbs').children()
					.eq(prevIndex).fadeTo('fast', onMouseOutOpacity).end()
					.eq(nextIndex).fadeTo('fast', 1.0);
			},
			onPageTransitionOut:       function(callback) {
				this.fadeTo('fast', 0.0, callback);
			},
			onPageTransitionIn:        function() {
				this.fadeTo('fast', 1.0);
			}
		});
	});
</script>

app/views/searchresults/edit.html.erb
<h1>Editing searchresult</h1>

<%= render 'form' %>

<%= link_to 'Show', @searchresult %> |
<%= link_to 'Back', searchresults_path %>

app/views/searchresults/index.html.erb
<h1>Listing searchresults</h1>

<table>
  <tr>
    <th>Realtytype</th>
    <th>Location</th>
    <th>Roomcount</th>
    <th>Priceline</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @searchresults.each do |searchresult| %>
  <tr>
    <td><%= searchresult.realtytype %></td>
    <td><%= searchresult.location %></td>
    <td><%= searchresult.roomcount %></td>
    <td><%= searchresult.priceline %></td>
    <td><%= link_to 'Show', searchresult %></td>
    <td><%= link_to 'Edit', edit_searchresult_path(searchresult) %></td>
    <td><%= link_to 'Destroy', searchresult, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Searchresult', new_searchresult_path %>

app/views/searchresults/new.html.erb
<%#= javascript_include_tag "mobilyslider.js" %>
<%#= stylesheet_link_tag    "slider" %>
<script>
$(function(){

	$('.slider1').mobilyslider({
      content: '.sliderContent', 		// класс для контейнера слайдера
      children: 'div', 					// селектор слайдов
      transition: 'fade', 			// эффект перехода между слайдами: horizontal, vertical, fade
      animationSpeed: 1500, 				// скорость перехода между слайдами в ms
      autoplay: true,					// включение автопроигрывания
      autoplaySpeed: 2900, 				// время показа слайда в ms
      pauseOnHover: false, 				// остановка автопроигрывания при наведении курсора мыши
      bullets: true, 					// генерация указателя слайдов (true/false, класс: sliderBullets)
      arrows: true, 						// генерация стрелок вперед/назад (true/false, класс: sliderArrows)
      arrowsHide: false, 					// выводим стрелки только при наведении курсора мыши
      prev: 'prev', 						// имя класса для кнопки назад
      next: 'next', 						// имя класса для кнопки вперед
      animationStart: function(){}, 		// возвратная функция, которая вызывается при запуске перехода между слайдами
      animationComplete: function(){} 	// возвратная функция, которая вызывается после завершения перехода между слайдами
  });

});
</script>
<div class="left">
<div class="container_12 main_img_container">	
	<div class="slider slider1">
		<div class="sliderContent">
						    
			<div class="item" style="display: none;">
			    <div class="slider_container">
			    	<div class="body">
                          <div class="slider_image">
	                    	<img src="slider1.jpg" alt="недвижимость на кипре" />
						  </div>
							<h1></h1>							        
			         </div>
			     </div>
			   </div>
			
			<div class="item" style="display: none;">
			    <div class="slider_container">
			    	<div class="body">
                          <div class="slider_image">
	                    	<img src="slider2.jpg" alt="недвижимость на кипре" />
						  </div>
							<h1></h1>							        
			         </div>
			     </div>
			   </div>
			
			<div class="item" style="display: none;">
			    <div class="slider_container">
			    	<div class="body">
                          <div class="slider_image">
	                    	<img src="slider3.jpg" alt="недвижимость на кипре" />
						  </div>
							<h1></h1>							        
			         </div>
			     </div>
			   </div>
			
			<div class="item" style="display: none;">
			    <div class="slider_container">
			    	<div class="body">
                          <div class="slider_image">
	                    	<img src="slider4.jpg" alt="недвижимость на кипре" />
						  </div>
							<h1></h1>							        
			         </div>
			     </div>
			   </div>			
						    			
		</div>
	</div>	
 </div>

<div class="clear"></div>
<div class="bottom_shadow"></div>
</div>


<div class="right">
	<div class="search_container">

		<%= render 'form' %>

		<%#= link_to 'Back', searchresults_path %>
	</div>	
</div>
<div class="clear"></div>
<h1>Hаши лучшие предложения</h1>
</br>
<ul class="best_container">
	<% @properties.each do |property| %>
	<%-if property.onmain? %>
	<li>
		<div class="best_box">
			<div class="onmaim_img">
		  <%= link_to image_tag(property.photo.url(:onmaim)), property %>
		    </div>	
		  <%#= image_tag property.photo.url(:medium) %>			  	
	    </div>
	    <div class="best_shadow"> 
		</div>
		<h2><%= link_to property.name, property, :class=>"a_title" %></h2>
		<p><%= property.observe %></p>
	</li>
	<% end%>
	  <% end%>
	    <div class="clear"></div>
	</ul>
	   <div class="clear"></div>
<div class="clear hr"></div>	
<h1>Hедвижимость на Кипре</h1>
<p>Кипр – настоящая жемчужина Средиземноморья, привлекающая к себе миллионы гостей из разных стран мира. Кипр – остров умиротворения, любви и красоты, остров романтиков, радующихся жизни. Много веков назад этот остров заметили могущественные боги Олимпа, а ведь они могли выбрать только лучшее!</p>
<p>Покупка недвижимости на Кипре имеет множество преимуществ. Кипр - это 320 солнечных дней в году, мягкий климат, теплое море, живописная природа и прекрасная экология: здесь нет загрязняющих атмосферу промышленных предприятий. Остров славится древней историей и богатейшим культурным наследием. Это крупный туристический центр, а также деловой центр региона, здесь успешно развивается в том числе и украинский бизнес.</p>
<p>Многие украинские и российские граждане обрели здесь вторую родину, в крупных городах нередко можно услышать русскую речь. Здесь созданы прекрасные условия для жизни и ведения бизнеса, отдыха. Гостеприимство киприотов известно далеко за пределами страны, а к славянам здесь относятся особенно благожелательно, менталитет греков-киприотов близок славянскому.
</p>
<p>Система права, действующая на Кипре, имеет в своей основе английское право и считается наиболее надежной в мире. Недвижимость на Кипре приобретается на основе права собственности. Для иностранных инвесторов это очень важно. При покупке недвижимости на Кипре формальности для иностранцев необременительны, процедура оформления проста и прозрачна (подробнее о процедуре оформления - в разделе "Покупка и оформление недвижимости"). Налогообложение для владельцев недвижимости на Кипре очень логичное и понятное, а главное, не столь обременительное. Все эти факторы неизменно привлекают на Кипр покупателей недвижимости из России, Британии и других стран мира. Значительную долю покупателей недвижимости на Кипре занимают иностранцы</p>


<script type="text/javascript">
	$(document).ready(function(){	

		if (!$.browser.opera) {
    
			// select element styling
			$('select.select').each(function(){
				var title = $(this).attr('title');
				if( $('option:selected', this).val() != ''  ) title = $('option:selected',this).text();
				$(this)
					.css({'z-index':10,'opacity':0,'-khtml-appearance':'none'})
					.after('<span class="select">' + title + '</span>')
					.change(function(){
						val = $('option:selected',this).text();
						$(this).next().text(val);
						})
			});

		};
		
	});
</script>

app/views/searchresults/show.html.erb
<div class="sort"> 
<div class="left"><span> Результаты поиска </span></div>

	<div class="right"> 
<%= link_to "Посмотреть все предложения", "/catalog" %>
    </div>

<div class="clear"> </div>
</div>
<div class="clear"> </div>

<% @properties.each do |property| %>
  <div>    
    <%-if @searchresult.realtytype == property.realtytype and @searchresult.location == property.location and  @searchresult.roomcount == property.roomcount and @searchresult.priceline >= property.price %>
<!--_______________________________ start_________________________________-->  
    <div class="catalog_container">
	    <h1><%= link_to property.name, property, :class=>"a_title" %></h1>
	    <div class="c_photo left">
		  <div class="medium_img">
		  <%= image_tag property.photo.url(:medium) %>
		  </div>
		  
		</div>
		<div class="left">
		    <div class="direct_info">
				<p>
				  <b class="title">Место положения:</b>
				  <%= property.location %>
				</p>
				<p>
				  <b class="title">Количество спален:</b>
				  <%= property.roomcount %>
				</p>
				<p> <b class="title">Тип:</b>
				  <%= property.realtytype %>
				</p>
				<p> <b class="title c_price">Цена:</b>
				<%= property.price %>
				</p>
		    </div>
	    </div>
        <div class="left shortdescription">
	        <p>
            <%= simple_format(property.shortdescription) %>
            </p>  
        </div>
        <div class="clear"></div>
        <%= link_to "Подробнее", property , :class=> "more"%>
    </div>
<!---_______________________________ end _______________________________-->  
    <%-else%>
      <%-if (@searchresult.realtytype == property.realtytype and @searchresult.location == property.location and  @searchresult.roomcount == property.roomcount) or (@searchresult.realtytype == property.realtytype and @searchresult.location == property.location and @searchresult.priceline >= property.price)%>
<!--_______________________________ start_________________________________-->  
    <div class="catalog_container">
	    <h1><%= link_to property.name, property, :class=>"a_title" %></h1>
	    <div class="c_photo left">
		  <div class="medium_img">
		  <%= image_tag property.photo.url(:medium) %>
		  </div>
		</div>
		
		<div class="left">
		    <div class="direct_info">
				<p>
				  <b class="title">Место положения:</b>
				  <%= property.location %>
				</p>
				<p>
				  <b class="title">Количество спален:</b>
				  <%= property.roomcount %>
				</p>
				<p> <b class="title">Тип:</b>
				  <%= property.realtytype %>
				</p>
				<p> <b class="title c_price">Цена:</b>
				<%= property.price %>
				</p>
		    </div>
	    </div>
        <div class="left shortdescription">
	        <p>
            <%= simple_format(property.shortdescription) %>
            </p>  
        </div>
        <div class="clear"></div>
        <%= link_to "Подробнее", property , :class=> "more"%>
    </div>
<!---_______________________________ end _______________________________--> 
    <%-else%>
      <%-if (@searchresult.realtytype == property.realtytype and  @searchresult.roomcount == property.roomcount) or (@searchresult.realtytype == property.realtytype and @searchresult.location == property.location)%>
<!--_______________________________ start_________________________________-->  
    <div class="catalog_container">
	    <h1><%= link_to property.name, property, :class=>"a_title" %></h1>
	    <div class="c_photo left">
		  <div class="medium_img">
		  <%= image_tag property.photo.url(:medium) %>
		  </div>
		</div>
		
		<div class="left">
		    <div class="direct_info">
				<p>
				  <b class="title">Место положения:</b>
				  <%= property.location %>
				</p>
				<p>
				  <b class="title">Количество спален:</b>
				  <%= property.roomcount %>
				</p>
				<p> <b class="title">Тип:</b>
				  <%= property.realtytype %>
				</p>
				<p> <b class="title c_price">Цена:</b>
				<%= property.price %>
				</p>
		    </div>
	    </div>
        <div class="left shortdescription">
	        <p>
            <%= simple_format(property.shortdescription) %>
            </p>  
        </div>
        <div class="clear"></div>
        <%= link_to "Подробнее", property , :class=> "more"%>
    </div>
<!---_______________________________ end _______________________________-->     
        <%-end%>

	  <%-end%>
    
    <%-end %>
    
  </div>
<% end %>


<%#= link_to 'Edit', edit_searchresult_path(@searchresult) %> 
<%#= link_to 'Back', searchresults_path %>