config/routes.rb
Cyprussite::Application.routes.draw do
  get "contact/index"

  get "about/index"

  get "catalog/index"

  resources :properties

  resources :searchresults
  
  root :to => "searchresults#new"
  resources :catalog
  match '/catalog_price' => 'catalog#price'
  match '/catalog_type' => 'catalog#type'

  match '/about' => 'about#index'
  resources :contact
  
  

end

app/models/property.rb
class Property < ActiveRecord::Base
  has_attached_file :photo, :styles => { :small => "93>x53", :medium => "154>x88", :onmaim => "174>x94" },                    
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/s3.yml",
                    :url  => "/:id/:style/:basename.:extension",
                    :path => ":id/:style/:basename.:extension",
                    :bucket => 'photos.domnakipre.com.ua'
                    

  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
  
  has_attached_file :photo1, :styles => { :small => "93>x53", :medium => "154>x88", :onmaim => "174>x94" },
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/s3.yml",
                    :url  => "/:id/:style/:basename.:extension",
                    :path => ":id/:style/:basename.:extension",
                    :bucket => 'photos.domnakipre.com.ua'

  validates_attachment_content_type :photo1, :content_type => ['image/jpeg', 'image/png']

  has_attached_file :photo2, :styles => { :small => "93>x53", :medium => "154>x88", :onmaim => "174>x94" },
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/s3.yml",
                    :url  => "/:id/:style/:basename.:extension",
                    :path => ":id/:style/:basename.:extension",
                    :bucket => 'photos.domnakipre.com.ua'

  validates_attachment_content_type :photo2, :content_type => ['image/jpeg', 'image/png']

  has_attached_file :photo3, :styles => { :small => "93>x53", :medium => "154>x88", :onmaim => "174>x94" },
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/s3.yml",
                    :url  => "/:id/:style/:basename.:extension",
                    :path => ":id/:style/:basename.:extension",
                    :bucket => 'photos.domnakipre.com.ua'

  validates_attachment_content_type :photo3, :content_type => ['image/jpeg', 'image/png']

  has_attached_file :photo4, :styles => { :small => "93>x53", :medium => "154>x88", :onmaim => "174>x94" },
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/s3.yml",
                    :url  => "/:id/:style/:basename.:extension",
                    :path => ":id/:style/:basename.:extension",
                    :bucket => 'photos.domnakipre.com.ua'

  validates_attachment_content_type :photo4, :content_type => ['image/jpeg', 'image/png']

  has_attached_file :photo5, :styles => { :small => "93>x53", :medium => "154>x88", :onmaim => "174>x94"},
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/s3.yml",
                    :url  => "/:id/:style/:basename.:extension",
                    :path => ":id/:style/:basename.:extension",
                    :bucket => 'photos.domnakipre.com.ua'

  validates_attachment_content_type :photo5, :content_type => ['image/jpeg', 'image/png']

  has_attached_file :photo6, :styles => { :small => "93>x53", :medium => "154>x88",  :onmaim => "174>x94" },
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/s3.yml",
                    :url  => "/:id/:style/:basename.:extension",
                    :path => ":id/:style/:basename.:extension",
                    :bucket => 'photos.domnakipre.com.ua'

  validates_attachment_content_type :photo6, :content_type => ['image/jpeg', 'image/png']

  has_attached_file :photo7, :styles => { :small => "93>x53", :medium => "154>x88",  :onmaim => "174>x94" },
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/s3.yml",
                    :url  => "/:style/:basename.:extension",
                    :path => ":style/:basename.:extension",
                    :bucket => 'photos.domnakipre.com.ua'

  validates_attachment_content_type :photo7, :content_type => ['image/jpeg', 'image/png']

  
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  # http_basic_authenticate_with :name => "ksenia", :password => "jj567858", :except => :new
  # GET /properties
  # GET /properties.json
  before_filter :find_all_properties
  def index
    @properties = Property.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @properties }
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/new
  # GET /properties/new.json
  def new
    @property = Property.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/1/edit
  def edit
    @property = Property.find(params[:id])
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(params[:property])

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render json: @property, status: :created, location: @property }
      else
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.json
  def update
    @property = Property.find(params[:id])

    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :no_content }
    end
  end
  protected

    def find_all_properties
      @properties = Property.order()
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
 <div class="field">
  <%= f.file_field :photo %>
   </div>
 <div class="field">
  <%= f.file_field :photo1 %>
   </div>
 <div class="field">
  <%= f.file_field :photo2 %>
   </div>
 <div class="field">
  <%= f.file_field :photo3 %>
   </div>
 <div class="field">
  <%= f.file_field :photo4 %>
   </div>
 <div class="field">
  <%= f.file_field :photo5 %>
   </div>
 <div class="field">
  <%= f.file_field :photo6 %>
   </div>
 <div class="field">
  <%= f.file_field :photo7 %>
   </div>


  <div class="field">
    <%= f.label :codename %><br />
    <%= f.text_field :codename %>
  </div>
  <div class="field">
    <%= f.label :realtytype %><br />
    <%= f.select("realtytype", ['аппартаменты', 'офис', 'дом', 'мезоньет', 'другое'], {}, { :class => 'select' })%>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.select("location", ['Лимассол'])%>
  </div>
  <div class="field">
    <%= f.label :roomcount %><br /> 
    <%= f.select("roomcount", ['не важно', '2 спальни', '3 спальни', '4 спальни', '5 спален', '6 спален'], {}, { :class => 'select' })%>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :fulldescription %><br />
    <%= f.text_area :fulldescription %>
  </div>
  <div class="field">
    <%= f.label :observe %><br />
    <%= f.text_area :observe %>
  </div>
  <div class="field">
    <%= f.label :shortdescription %><br />
    <%= f.text_area :shortdescription %>
  </div>
  <div class="field">
    <%= f.label :onmain %><br />
    <%= f.check_box :onmain %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<h1>Listing properties</h1>
<% @properties.each do |property| %>
  
    
    <div class="td"><b>Name</b></br><%= property.name %></div>
    <div class="td">
    <%- if property.photo?%>
    <div class="left"><%= image_tag property.photo.url(:small) %></div>
     <%- end%>
    <%- if property.photo1?%>
    <div class="left"><%= image_tag property.photo1.url(:small) %></div>    
    <%- end%>
     <div class="clear"></div>
    </div>
    <div class="td"><b>Realtytype</b></br><%= property.realtytype %></div>
    <div class="td"><b>Location</b></br><%= property.location %></div>
    <div class="td"><b>Roomcount</b></br><%= property.roomcount %></div>
    <div class="td"><b>Price</b></br><%= property.price %></div>
    <div class="td"><b>Fulldescription</b></br><%= property.fulldescription %></div>
    <div class="td"><b>Observe</b></br><%= property.observe %></div>
    <div class="td"><b>Shortdescription</b></br><%= property.shortdescription %></div>
    <div class="td"><b>Onmain</b></br><%= property.onmain %></div>

    	<div class="td"><%= link_to 'Show', property %> | <%= link_to 'Edit', edit_property_path(property) %> | <%= link_to 'Destroy', property, confirm: 'Are you sure?', method: :delete %></div>
  <div class="hr"></div>
  
<% end %>

<br />

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<!-- We only want the thunbnails to display when javascript is disabled -->
<script type="text/javascript">
	document.write('<style>.noscript { display: none; }</style>');
</script>
<div class="right">
	<div class="images_galery">
		
		<!-- Start Advanced Gallery Html Containers -->
		<div id="gallery" class="content">
			<div class="img_shadow"></div>
			<div id="controls" class="controls"></div>
			<div class="slideshow-container">
				<div id="loading" class="loader"></div>
				<div id="slideshow" class="slideshow"></div>
			</div>

		</div>
		<div id="thumbs" class="navigation">
			<ul class="thumbs noscript">
				<li>
					
					<a class="thumb" name="leaf"  href="<%= url_for @property.photo.url%>" title="Title #0">
						<div class="small_img">
						<%= image_tag @property.photo.url(:small) %>
						</div>
					</a>
					<div class="caption">
						<div class="download">
							<a href= "<%= url_for @property.photo.url%>"> </a>
							
						</div>
					</div>
				</li>
                <%-if @property.photo1? %>
				<li>
					<a class="thumb" name="drop" href="<%= url_for @property.photo1.url%>" title="Title #1">
						<div class="small_img">
						<%= image_tag @property.photo1.url(:small)%>
                        </div>						
					</a>
					<div class="download">
						<a href= "<%= url_for @property.photo1.url%>"> </a>
					</div>
					
				</li>
				<%-end%>
                <%-if @property.photo2? %>
				<li>
					<a class="thumb" href="<%= url_for @property.photo2.url%>" title="Title #2">
						<div class="small_img">
						<%= image_tag @property.photo2.url(:small)%>
                        </div>
					</a>
					<div class="caption">
						<div class="download">
							<a href= "<%= url_for @property.photo2.url%>"> </a>
						</div>
					</div>
				</li>
				<%-end%> 
                <%-if @property.photo3? %>
				<li class="li_last">
					<a class="thumb" href="<%= url_for @property.photo3.url%>" title="Title #3">
						<div class="small_img">
						<%= image_tag @property.photo3.url(:small)%>
                        </div>
					</a>
					<div class="caption">
						<div class="download">
							<a href= "<%= url_for @property.photo3.url%>"> </a>
						</div>
					</div>
				</li>
				<%-end%> 
                <%-if @property.photo4? %>
				<li>
					<a class="thumb" href="<%= url_for @property.photo4.url%>" title="Title #4">
						<div class="small_img">
						<%= image_tag @property.photo4.url(:small)%>
                        </div>
					</a>
					<div class="caption">
						<div class="download">
							<a href= "<%= url_for @property.photo4.url%>"> </a>
						</div>
					</div>
				</li>
				<%-end%> 
				<%-if @property.photo5? %>
				<li>
					<a class="thumb" href="<%= url_for @property.photo5.url%>" title="Title #5">
						<div class="small_img">
						<%= image_tag @property.photo5.url(:small)%>
                        </div>
					</a>
					<div class="caption">
						<div class="download">
							<a href= "<%= url_for @property.photo5.url%>"> </a>
						</div>
					</div>
				</li>
				    <%-end%>
                    <%-if @property.photo6? %>
					<li>
						<a class="thumb" href="<%= url_for @property.photo6.url%>" title="Title #6">
							<div class="small_img">
							<%= image_tag @property.photo6.url(:small)%>
                            </div>
						</a>
						<div class="caption">
							<div class="download">
								<a href= "<%= url_for @property.photo6.url%>"> </a>
							</div>
						</div>
					</li>
					<%-end%>
					<%-if @property.photo7? %>

				<li class="li_last">
					<a class="thumb" href="<%= url_for @property.photo7.url%>" title="Title #7">
						<div class="small_img">
						<%= image_tag @property.photo7.url(:small) %>
						</div>
					</a>
					<div class="caption">
						<div class="download">
							<a href= "<%= url_for @property.photo7.url%>"> </a>
						</div>
						<!-- <div class="image-title">Title #7</div>
						<div class="image-desc">Description</div>-->
					</div>
				</li>
				<%-end%>
			</ul>
		</div>
		<div style="clear: both;"></div>
	</div>
</div>




<div class="left show_info">



<h1>
  <%= @property.name %>
</h1>
<div class="direct_info">
<p>
  <b class="title">Место положения:</b>
  <%= @property.location %>
</p>
<p>
  <b class="title">Количество спален:</b>
  <%= @property.roomcount %>
</p>
<p> <b class="title">Тип:</b>
  <%= @property.realtytype %>
</p>
</div>

<div class="price_box">
  <%= @property.price %> Euro
</div>
<div class="hr"></div>
<p>
  <%= simple_format(@property.fulldescription) %>
</p>
<p>
   INFORMATION
</p>
</div>
<div style="clear: both;"></div>


<%#= link_to 'Edit', edit_property_path(@property) %>
<%#= link_to 'Back', properties_path %>





<script type="text/javascript">
	jQuery(document).ready(function($) {
		// We only want these styles applied when javascript is enabled
		$('div.navigation').css({'width' : '443px', 'display' : 'block'});
		$('div.content').css('display', 'block');

		// Initially set opacity on thumbs and add
		// additional styling for hover effect on thumbs
		var onMouseOutOpacity = 0.67;
		$('#thumbs ul.thumbs li').opacityrollover({
			mouseOutOpacity:   onMouseOutOpacity,
			mouseOverOpacity:  1.0,
			fadeSpeed:         'fast',
			exemptionSelector: '.selected'
		});
		
		// Initialize Advanced Galleriffic Gallery
		var gallery = $('#thumbs').galleriffic({
			delay:                     2500,
			numThumbs:                 15,
			preloadAhead:              10,
			enableTopPager:            true,
			enableBottomPager:         true,
			maxPagesToShow:            7,
			imageContainerSel:         '#slideshow',
			controlsContainerSel:      '#controls',
			captionContainerSel:       '#caption',
			loadingContainerSel:       '#loading',
			renderSSControls:          true,
			renderNavControls:         true,
			playLinkText:              'Play Slideshow',
			pauseLinkText:             'Pause Slideshow',
			prevLinkText:              '',
			nextLinkText:              '',
			nextPageLinkText:          'Next &rsaquo;',
			prevPageLinkText:          '&lsaquo; Prev',
			enableHistory:             false,
			autoStart:                 false,
			syncTransitions:           true,
			defaultTransitionDuration: 900,
			onSlideChange:             function(prevIndex, nextIndex) {
				// 'this' refers to the gallery, which is an extension of $('#thumbs')
				this.find('ul.thumbs').children()
					.eq(prevIndex).fadeTo('fast', onMouseOutOpacity).end()
					.eq(nextIndex).fadeTo('fast', 1.0);
			},
			onPageTransitionOut:       function(callback) {
				this.fadeTo('fast', 0.0, callback);
			},
			onPageTransitionIn:        function() {
				this.fadeTo('fast', 1.0);
			}
		});
	});
</script>